version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - echo Checking Node.js and Yarn versions...
      - node -v
      - npm -v
      - yarn -v || npm install -g yarn

  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install

  build:
    commands:
      - echo Build started on `date`
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
